// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piglspfljaivtucfowxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpZ2xzcGZsamFpdnR1Y2Zvd3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjM5MDIsImV4cCI6MjA2MDAzOTkwMn0.2WCCGqCXRBAfwttKOrHJZJJmJT3GOf5vfCTggG9evFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);